package in.co.exception;

public class TryFinally {
	public static void main(String[] args) {
		try {
			double div =15/5;
			System.out.println("hello");
		}finally {
			System.out.println("bye");
			}
		}

}
